In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [6]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
## preprocess the data
## drop irrelevant the data
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [8]:
## Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [10]:
## OneHot Encoding for the Geography
onehot_encoder_geo=OneHotEncoder(handle_unknown='ignore')
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [11]:
 ## combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [12]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [13]:
## Divide the dataset into independent and dependent features
# split the data into features and target
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [15]:
## save the encoders and scaler for later use

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb')as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### Train ANN Rgeression Problem Statement

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)   ## when no activation function apply in output layer...then by default linear activation function aplied
    # Output layer for regression
])

## compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

model.summary()

c:\Users\PANDURANG\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
## Set up the TensorBoard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callbacks=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [19]:
## Set up early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [20]:
## train the model

### Train the model

history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[tensorflow_callbacks,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100377.4375 - mae: 100377.4375 - val_loss: 98518.7891 - val_mae: 98518.7891
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99663.8203 - mae: 99663.8203 - val_loss: 97087.4219 - val_mae: 97087.4219
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97205.0625 - mae: 97205.0625 - val_loss: 93477.2031 - val_mae: 93477.2031
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92367.5312 - mae: 92367.5312 - val_loss: 87344.9062 - val_mae: 87344.9062
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 85092.0625 - mae: 85092.0625 - val_loss: 79184.5625 - val_mae: 79184.5625
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 76244.7344 - mae: 76244.7344 - val_loss: 70351.4141 - val_mae: 70351.4141
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 67422.1484 - mae: 67422.1484 - val_loss: 62532.5156 - val_mae: 62532.5156
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 60089.5664 - mae: 60089.5664 - val_loss: 56702.4922 - val_mae: 56702.4922
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55098.1172 - mae: 55098.1172 - val_loss: 53154.8516 - val_mae: 53154.8516
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52263.8711 - mae: 52263.8711 - val_loss: 51568.0977 - val_mae: 51568.0977
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50991.1719 - mae: 50991.1719 - val_loss: 50995.9375 - val_mae: 50995.9375
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50467.3789 - mae: 50467.3789 - val_loss: 50792.4062 - val_mae: 50792.4062
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50254.0039 - mae: 50254.0039 - val_loss: 50704.8008 - val_mae: 50704.8008
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50149.1016 - mae: 50149.1016 - val_loss: 50642.4609 - val_mae: 50642.4609
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50082.1914 - mae: 50082.1914 - val_loss: 50591.5078 - val_mae: 50591.5078
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50031.8086 - mae: 50031.8086 - val_loss: 50546.7656 - val_mae: 50546.7656
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49989.8398 - mae: 49989.8398 - val_loss: 50516.9492 - val_mae: 50516.9492
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49950.4453 - mae: 49950.4453 - val_loss: 50489.9023 - val_mae: 50489.9023
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49914.6719 - mae: 49914.6719 - val_loss: 50472.4883 - val_mae: 50472.4883
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49887.0742 - mae: 49887.0742 - val_loss: 50456.5859 - val_mae: 50456.5859
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49857.1719 - mae: 49857.1719 - val_loss: 50430.8867 - val_mae: 50430.8867
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49828.7695 - mae: 49828.7695 - val_loss: 50418.3203 - val_mae: 50418.3203
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49804.1562 - mae: 49804.1562 - val_loss: 50404.7422 - val_mae: 50404.7422
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49782.8594 - mae: 49782.8594 - val_loss: 50393.4570 - val_mae: 50393.4570
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49758.6562 - mae: 49758.6562 - val_loss: 50383.6836 - val_mae: 50383.6836
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49738.5742 - mae: 49738.5742 - val_loss: 50369.4648 - val_mae: 50369.4648
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49717.8906 - mae: 49717.8906 - val_loss: 50365.8438 - val_mae: 50365.8438
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49700.8867 - mae: 49700.8867 - val_loss: 50356.0156 - val_mae: 50356.0156
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49685.8203 - mae: 49685.8203 - val_loss: 50350.6602 - val_mae: 50350.6602
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49669.0000 - mae: 49669.0000 - val_loss: 50342.6602 - val_mae: 50342.6602
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49656.6914 - mae: 49656.6914 - val_loss: 50341.7617 - val_mae: 50341.7617
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49642.3242 - mae: 49642.3242 - val_loss: 50330.6367 - val_mae: 50330.6367
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49628.3398 - mae: 49628.3398 - val_loss: 50321.3516 - val_mae: 50321.3516
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49617.3555 - mae: 49617.3555 - val_loss: 50320.8438 - val_mae: 50320.8438
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49604.9492 - mae: 49604.9492 - val_loss: 50327.7188 - val_mae: 50327.7188
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49592.9141 - mae: 49592.9141 - val_loss: 50316.1055 - val_mae: 50316.1055
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49584.3359 - mae: 49584.3359 - val_loss: 50319.5039 - val_mae: 50319.5039
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49573.1211 - mae: 49573.1211 - val_loss: 50310.0273 - val_mae: 50310.0273
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49562.9492 - mae: 49562.9492 - val_loss: 50307.4414 - val_mae: 50307.4414
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49553.1406 - mae: 49553.1406 - val_loss: 50308.1758 - val_mae: 50308.1758
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49545.1211 - mae: 49545.1211 - val_loss: 50306.7578 - val_mae: 50306.7578
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49536.7070 - mae: 49536.7070 - val_loss: 50309.2969 - val_mae: 50309.2969
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49525.8281 - mae: 49525.8281 - val_loss: 50306.1953 - val_mae: 50306.1953
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49518.8750 - mae: 49518.8750 - val_loss: 50309.2812 - val_mae: 50309.2812
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49509.4766 - mae: 49509.4766 - val_loss: 50307.3711 - val_mae: 50307.3711
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49502.6406 - mae: 49502.6406 - val_loss: 50301.9648 - val_mae: 50301.9648
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49492.3047 - mae: 49492.3047 - val_loss: 50300.3672 - val_mae: 50300.3672
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49484.9805 - mae: 49484.9805 - val_loss: 50299.6055 - val_mae: 50299.6055
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49478.4609 - mae: 49478.4609 - val_loss: 50302.0742 - val_mae: 50302.0742
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49472.8398 - mae: 49472.8398 - val_loss: 50301.9219 - val_mae: 50301.9219
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49468.2773 - mae: 49468.2773 - val_loss: 50305.7891 - val_mae: 50305.7891
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49463.1250 - mae: 49463.1250 - val_loss: 50301.1523 - val_mae: 50301.1523
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49453.0156 - mae: 49453.0156 - val_loss: 50298.9844 - val_mae: 50298.9844
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49449.8438 - mae: 49449.8438 - val_loss: 50306.1641 - val_mae: 50306.1641
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49442.1562 - mae: 49442.1562 - val_loss: 50306.3320 - val_mae: 50306.3320
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49438.5977 - mae: 49438.5977 - val_loss: 50298.2461 - val_mae: 50298.2461
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49431.6523 - mae: 49431.6523 - val_loss: 50288.3828 - val_mae: 50288.3828
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49426.4805 - mae: 49426.4805 - val_loss: 50290.3398 - val_mae: 50290.3398
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49419.2461 - mae: 49419.2461 - val_loss: 50295.6992 - val_mae: 50295.6992
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49415.5156 - mae: 49415.5156 - val_loss: 50288.3945 - val_mae: 50288.3945
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49409.7383 - mae: 49409.7383 - val_loss: 50298.3867 - val_mae: 50298.3867
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49405.8164 - mae: 49405.8164 - val_loss: 50294.4023 - val_mae: 50294.4023
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49400.3086 - mae: 49400.3086 - val_loss: 50299.6562 - val_mae: 50299.6562
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49395.2578 - mae: 49395.2578 - val_loss: 50295.0469 - val_mae: 50295.0469
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49392.3398 - mae: 49392.3398 - val_loss: 50289.2617 - val_mae: 50289.2617
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49387.3594 - mae: 49387.3594 - val_loss: 50290.0430 - val_mae: 50290.0430
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49382.3633 - mae: 49382.3633 - val_loss: 50292.9062 - val_mae: 50292.9062

In [21]:
%load_ext tensorboard

In [22]:
%tensorboard --logdir regressionlogs/fit

In [23]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50288.3828 - mae: 50288.3828
Test MAE : 50288.3828125

In [24]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.